### ISSUE TITLE
TypeError: handler.state is not a function on build

### ISSUE THREAD

**Issue by fernandomora** [butterproject/butter-desktop#418]
When I follow instructions to build and run the project I receive the following error:
``` 
$ gulp build
(node:50631) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:50631) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[00:40:14] Using gulpfile ~/git/butter-desktop/gulpfile.js
[00:40:14] Starting 'build'...
[00:40:14] Starting 'injectgit'...
Branch: master
Commit: e3da5178
[00:40:14] Finished 'injectgit' after 19 ms
[00:40:14] Starting 'css'...
Stylus files compiled in ~/git/butter-desktop/src/app/themes/
[00:40:19] Finished 'css' after 4.86 s
[00:40:19] Starting 'nwjs'...
[00:40:53] 'nwjs' errored after 34 s
[00:40:53] TypeError: handler.state is not a function
    at Object.inspect (~/git/butter-desktop/node_modules/when/lib/state.js:28:23)
    at formatValue (util.js:348:21)
    at formatProperty (util.js:777:15)
    at util.js:637:12
    at Array.map (native)
    at formatObject (util.js:636:15)
    at formatValue (util.js:575:16)
    at formatProperty (util.js:777:15)
    at util.js:637:12
    at Array.map (native)
    at formatObject (util.js:636:15)
    at formatValue (util.js:575:16)
    at formatProperty (util.js:777:15)
    at util.js:637:12
    at Array.map (native)
    at formatObject (util.js:636:15)
[00:40:53] 'build' errored after 39 s
[00:40:53] TypeError in plugin 'run-sequence(nwjs)'
Message:
    handler.state is not a function
Stack:
TypeError: handler.state is not a function
    at Object.inspect (~/git/butter-desktop/node_modules/when/lib/state.js:28:23)
    at formatValue (util.js:348:21)
    at formatProperty (util.js:777:15)
    at util.js:637:12
    at Array.map (native)
    at formatObject (util.js:636:15)
    at formatValue (util.js:575:16)
    at formatProperty (util.js:777:15)
    at util.js:637:12
    at Array.map (native)
    at formatObject (util.js:636:15)
    at formatValue (util.js:575:16)
    at formatProperty (util.js:777:15)
    at util.js:637:12
    at Array.map (native)
    at formatObject (util.js:636:15)
```

Same error is happening in every CI build since [build \#711](https://travis-ci.org/butterproject/butter-desktop/builds/141877974#L1440) although build is, probably wrongly, passing.

**Comment by vankasteelj** [comment]
Mh, thanks for reporting, it must be the nw-builder update screwing around (or the old version we use being deprecated).

**Comment by vankasteelj** [comment]
I believe the issue comes from nw-builder being passed from 2.2.0 to 2.2.5 with breaking changes (should have been 3.0.0). I'm testing.

**Comment by vankasteelj** [comment]
I forgot to update you, you can remove the nw-builder module and redownload it (it's now fixed in v2.2.0)

**Comment by EdwinOtten** [comment]
I'm on v2.2.0 but still having the same error, that's with node v4.4.7 by the way. I am using the latest master, which currently is your commit that would fix the issue (3eb0884).
@vankasteelj Any clue what this might be?

```
C:\Users\Edwin\Documents\GitHub\butter-desktop>npm -v
3.10.5

C:\Users\Edwin\Documents\GitHub\butter-desktop>node -v
v4.4.7

C:\Users\Edwin\Documents\GitHub\butter-desktop>npm list nw-builder
Butter@0.3.8-5a C:\Users\Edwin\Documents\GitHub\butter-desktop
`-- nw-builder@2.2.0


C:\Users\Edwin\Documents\GitHub\butter-desktop>gulp build
[20:42:42] Using gulpfile ~\Documents\GitHub\butter-desktop\gulpfile.js
[20:42:42] Starting 'build'...
[20:42:42] Starting 'injectgit'...
Branch: master
Commit: 3eb08840
[20:42:43] Finished 'injectgit' after 67 ms
[20:42:43] Starting 'css'...
Stylus files compiled in C:\Users\Edwin\Documents\GitHub\butter-desktop\src\app\themes\
[20:42:48] Finished 'css' after 5.18 s
[20:42:48] Starting 'nwjs'...
[20:42:54] 'nwjs' errored after 6.63 s
[20:42:54] TypeError: handler.state is not a function
    at Object.inspect (C:\Users\Edwin\Documents\GitHub\butter-desktop\node_modules\gulp-stylus\node_modules\accord\node_modules\when\lib\state.js:28:23)
    at formatValue (util.js:219:21)
    at formatProperty (util.js:584:15)
    at util.js:468:12
    at Array.map (native)
    at formatObject (util.js:467:15)
    at formatValue (util.js:410:16)
    at formatProperty (util.js:584:15)
    at util.js:468:12
    at Array.map (native)
[20:42:54] 'build' errored after 12 s
[20:42:54] TypeError in plugin 'run-sequence(nwjs)'
Message:
    handler.state is not a function
Stack:
TypeError: handler.state is not a function
    at Object.inspect (C:\Users\Edwin\Documents\GitHub\butter-desktop\node_modules\gulp-stylus\node_modules\accord\node_modules\when\lib\state.js:28:23)
    at formatValue (util.js:219:21)
    at formatProperty (util.js:584:15)
    at util.js:468:12
    at Array.map (native)
    at formatObject (util.js:467:15)
    at formatValue (util.js:410:16)
    at formatProperty (util.js:584:15)
    at util.js:468:12
    at Array.map (native)
```

**Comment by vankasteelj** [comment]
When using recent versions of npm (that "flattens" the dependencies) it's best to redownload all of them, to avoid these kind of issues. If you completely delete `node_modules` and redo `npm install`, does it work?

**Comment by EdwinOtten** [comment]
That did the trick! Also, I was on very old versions of npm and node when I first tried ``npm install`` and gulp build so the stuff in node_modules was probably outdated. It builds and runs now.
